import { ArrowDownRight, ArrowUpRight, ChevronRight, Landmark, RefreshCw, ShieldCheck } from "lucide-react";
import { MarketFooter } from "@/components/MarketFooter";
import { MarketHeader } from "@/components/MarketHeader";
import { formatCompactNumber, formatPercent, formatUpdated, formatUsd } from "@/lib/marketFormat";
import { trpc } from "@/lib/trpc";

function PairChange({ value }: { value: number }) { const positive = value >= 0; return <span className={positive ? "change-value is-positive" : "change-value is-negative"}>{positive ? <ArrowUpRight size={12} /> : <ArrowDownRight size={12} />}{formatPercent(value)}</span>; }

export default function Exchanges() {
  const exchanges = trpc.market.exchanges.useQuery(undefined, { staleTime: 15_000, refetchInterval: 20_000, retry: 1 });
  const binancePairs = exchanges.data?.binance.pairs ?? [];
  const coinbasePairs = exchanges.data?.coinbase.pairs ?? [];
  return <div className="light-app-shell"><MarketHeader active="exchanges" /><main className="data-page">
    <section className="data-page-head"><div><div className="page-overline"><span className="status-dot-light" /> MULTI-PROVIDER EXCHANGE DATA</div><h1>Crypto exchanges</h1><p>Compare exchange activity and inspect separate, read-only spot market pulses from Binance and Coinbase.</p></div><div className="page-status"><span className={exchanges.isFetching ? "status-pulse is-refreshing" : "status-pulse"} /><span>{exchanges.data ? `CoinGecko + Binance + Coinbase · ${formatUpdated(exchanges.data.updatedAt)}` : "Connecting to providers"}</span></div></section>
    <section className="exchange-hero-grid" id="provider-status"><article className="exchange-pulse-card"><div className="exchange-card-label"><span className="status-dot-light" /> BINANCE SPOT PULSE</div><h2>Most active USDT pairs</h2><p>Public 24-hour ticker data. No account or trading permission is used.</p><div className="pair-list">{binancePairs.slice(0, 6).map((pair) => <div className="pair-row" key={pair.symbol}><strong>{pair.symbol}</strong><span>{formatUsd(pair.price)}</span><PairChange value={pair.change24h} /></div>)}</div>{!binancePairs.length && <div className="pair-empty">Binance data is temporarily unavailable.</div>}</article><article className="exchange-summary-card"><span className="card-overline">COINBASE SPOT PULSE</span><h2>Most active USD / USDC pairs</h2><p>Public product data is read independently and displayed beside Binance without blending exchange prices.</p><div className="coinbase-pulse-list">{coinbasePairs.slice(0, 5).map((pair) => <div key={pair.symbol}><strong>{pair.symbol}</strong><span>{formatUsd(pair.price)}</span><PairChange value={pair.change24h} /></div>)}</div>{!coinbasePairs.length && <div className="pair-empty">Coinbase data is temporarily unavailable.</div>}<div><span><ShieldCheck size={15} /> Read-only</span><span><Landmark size={15} /> Provider-normalized</span></div></article></section>
    {exchanges.isError ? <section className="market-error"><Landmark size={22} /><div><strong>Exchange rankings are temporarily unavailable.</strong><p>{exchanges.error.message || "The provider did not return a usable response. Try refreshing the page."}</p></div><button className="outline-button" onClick={() => exchanges.refetch()}><RefreshCw size={14} /> Retry</button></section> : <section className="exchange-grid">{(exchanges.data?.exchanges ?? Array.from({ length: 12 })).map((exchange, index) => exchange ? <article className="exchange-card" key={exchange.id}><div className="exchange-card-top"><span className="exchange-rank">#{exchange.trustRank ?? index + 1}</span><span className="exchange-fallback">{exchange.name.slice(0, 1)}</span></div><h2>{exchange.name}</h2><span className="exchange-country">{exchange.country ?? "Global"}</span><div className="exchange-stat"><span>24h volume</span><strong>{formatCompactNumber(exchange.volumeBtc)} BTC</strong></div><div className="exchange-card-foot"><span>Trust score {exchange.trustScore ?? "—"}/10</span><button className="category-link">Details <ChevronRight size={14} /></button></div></article> : <article className="exchange-card category-skeleton" key={index}><span /><span /><span /></article>)}</section>}
    <MarketFooter />
  </main></div>;
}
