import { MarketFooter } from "@/components/MarketFooter";
import { MarketHeader } from "@/components/MarketHeader";
import { researchTopics } from "@/lib/researchTopics";
import { ArrowRight, BookOpen, CircleAlert, LibraryBig, Sparkles } from "lucide-react";
import { Link } from "wouter";

const guideLabels = ["Foundations", "Token design", "Market structure", "Market literacy", "Protocol basics", "Security"];

export default function Learn() {
  return <div className="light-app-shell"><MarketHeader active="learn" /><main className="data-page learn-page"><section className="learn-hero bold-hero"><div><div className="page-overline"><span className="status-dot-light" /> CRYPTOLENS RESEARCH</div><h1>Read the market<br /><em>with sharper questions.</em></h1><p>Detailed, original research frames for moving from a headline number to a more disciplined market review.</p><div className="learn-hero-note"><CircleAlert size={15} /><span>Educational context only. These guides are not financial, legal, or investment advice.</span></div></div><div className="learn-hero-stat"><LibraryBig size={23} /><strong>{researchTopics.length}</strong><span>research briefs<br />for practical market reading</span></div></section><section className="research-filter-row" aria-label="Research categories">{guideLabels.map((label) => <span key={label}>{label}</span>)}</section><section className="research-topic-grid">{researchTopics.map((topic) => <article className="research-topic-card" key={topic.slug}><div className="research-card-top"><span>{topic.index}</span><strong>{topic.category}</strong></div><h2>{topic.title}</h2><p>{topic.dek}</p><div className="research-card-bottom"><span>Detailed guide</span><Link href={`/research/${topic.slug}`}>Read topic <ArrowRight size={14} /></Link></div></article>)}</section><section className="research-method-note"><div><Sparkles size={20} /><div><span className="card-overline">HOW TO USE THIS HUB</span><h2>Research is a sequence, not a prediction.</h2></div></div><p>Start with a live metric, open the matching research brief, verify what the number includes, and follow primary project documentation before forming an opinion.</p><Link href="/" className="outline-button">Open live rankings <ArrowRight size={14} /></Link></section><section className="learn-callout"><BookOpen size={24} /><div><span className="card-overline">KEEP EXPLORING</span><h2>Use every detail page as a research launch point.</h2><p>Coin pages combine live metrics, supply context, source links, and an educational Islamic-ethics screen so you can trace a number back to the right questions.</p></div><Link href="/coin/bitcoin" className="header-button">Open Bitcoin detail</Link></section><MarketFooter /></main></div>;
}
