import { MarketFooter } from "@/components/MarketFooter";
import { MarketHeader } from "@/components/MarketHeader";
import { getResearchTopic } from "@/lib/researchTopics";
import { AlertTriangle, ArrowLeft, ArrowRight, BookOpenCheck, CheckCircle2, ExternalLink } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function ResearchDetail() {
  const [, params] = useRoute<{ slug: string }>("/research/:slug");
  const topic = getResearchTopic(params?.slug ?? "");

  if (!topic) return <div className="light-app-shell"><MarketHeader active="learn" /><main className="data-page"><section className="detail-error"><BookOpenCheck size={24} /><h1>Research topic unavailable.</h1><p>This guide may have moved or is not available in the current learning index.</p><Link href="/learn" className="outline-button"><ArrowLeft size={14} /> Back to research</Link></section><MarketFooter /></main></div>;

  return <div className="light-app-shell"><MarketHeader active="learn" /><main className="data-page research-detail-page"><Link href="/learn" className="detail-back"><ArrowLeft size={14} /> Research hub</Link><section className="research-detail-hero"><div><span className="research-topic-index">{topic.index}</span><div className="page-overline">{topic.category.toUpperCase()} <span>•</span> CRYPTOLENS RESEARCH</div><h1>{topic.title}</h1><p>{topic.dek}</p></div><aside><span className="card-overline">READ THIS WITH</span><p>Live market data, official project documentation, and your own risk review.</p><Link href={topic.liveHref} className="header-button">Open live context <ArrowRight size={14} /></Link></aside></section><section className="research-reading-grid"><article className="research-article"><div className="research-summary"><span className="card-overline">IN BRIEF</span><p>{topic.summary}</p></div>{topic.sections.map((section, index) => <section className="research-section" key={section.heading}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{section.heading}</h2><p>{section.body}</p></div></section>)}</article><aside className="research-aside"><article className="research-checklist"><div><BookOpenCheck size={18} /><span className="card-overline">RESEARCH CHECKLIST</span></div>{topic.checklist.map((item) => <p key={item}><CheckCircle2 size={14} /> {item}</p>)}</article><article className="research-caution"><AlertTriangle size={17} /><div><span className="card-overline">CONTEXT CHECK</span><p>{topic.caution}</p></div></article><article className="research-sources"><span className="card-overline">PRIMARY READING</span>{topic.sources.map((source) => <a key={source.href} href={source.href} target="_blank" rel="noreferrer">{source.label}<ExternalLink size={13} /></a>)}</article></aside></section><section className="research-next"><div><span className="page-overline">NEXT IN RESEARCH</span><h2>Keep the framework close to the live data.</h2><p>Open the market workspace to compare current provider-backed figures with the questions in this guide.</p></div><Link href={topic.liveHref} className="header-button">Explore market data <ArrowRight size={14} /></Link></section><MarketFooter /></main></div>;
}
