import { ENV } from "./_core/env";

type CoinGeckoMarket = { id: string; symbol: string; name: string; image?: string; current_price: number | null; market_cap: number | null; market_cap_rank: number | null; total_volume: number | null; price_change_percentage_24h: number | null; price_change_percentage_7d_in_currency?: number | null; sparkline_in_7d?: { price?: number[] }; last_updated?: string };
type CoinGeckoExchange = { id: string; name: string; image?: string; country?: string | null; trust_score?: number | null; trust_score_rank?: number | null; trade_volume_24h_btc?: number | null; url?: string };
type CoinGeckoCategory = { id: string; name: string; market_cap?: number | null; market_cap_change_24h?: number | null; top_3_coins?: string[] };
type BinanceTicker = { symbol: string; lastPrice: string; priceChangePercent: string; quoteVolume: string };
type CoinbaseProduct = { product_id: string; price: string; price_percentage_change_24h: string; approximate_quote_24h_volume?: string; product_type?: string; status?: string; quote_currency_id?: string };

export type MarketCoin = { id: string; rank: number; symbol: string; name: string; image?: string; price: number; marketCap: number; volume: number; change24h: number; change7d: number | null; sparkline: number[]; lastUpdated: string | null };
export type MarketCategory = { id: string; name: string; marketCap: number; change24h: number; topCoins: string[] };
export type ExchangeSummary = { id: string; name: string; image?: string; country: string | null; trustScore: number | null; trustRank: number | null; volumeBtc: number; url?: string };
export type BinancePair = { symbol: string; price: number; change24h: number; quoteVolume: number };
export type CoinbasePair = { symbol: string; price: number; change24h: number; quoteVolume: number };

type CacheEntry<T> = { expiresAt: number; value: T };
const cache = new Map<string, CacheEntry<unknown>>();
const COINGECKO_BASE_URL = "https://api.coingecko.com/api/v3";
const BINANCE_BASE_URL = "https://api.binance.com/api/v3";
const COINBASE_BASE_URL = "https://api.coinbase.com/api/v3/brokerage/market";
const MARKET_CACHE_MS = 55_000;

function finite(value: number | null | undefined) { return typeof value === "number" && Number.isFinite(value) ? value : 0; }
async function cached<T>(key: string, ttl: number, loader: () => Promise<T>): Promise<T> { const existing = cache.get(key) as CacheEntry<T> | undefined; if (existing && existing.expiresAt > Date.now()) return existing.value; const value = await loader(); cache.set(key, { value, expiresAt: Date.now() + ttl }); return value; }
async function requestJson<T>(url: string, headers: Record<string, string> = {}): Promise<T> { const response = await fetch(url, { headers: { accept: "application/json", ...headers } }); if (!response.ok) throw new Error(`Upstream request failed (${response.status})`); return (await response.json()) as T; }
function coinGeckoHeaders() { if (!ENV.coingeckoDemoApiKey) throw new Error("CoinGecko provider is not configured"); return { "x-cg-demo-api-key": ENV.coingeckoDemoApiKey }; }

export function normalizeCoins(records: CoinGeckoMarket[]): MarketCoin[] { return records.filter((record) => finite(record.current_price) > 0 && finite(record.market_cap) > 0).map((record, index) => ({ id: record.id, rank: record.market_cap_rank ?? index + 1, symbol: record.symbol.toUpperCase(), name: record.name, image: record.image, price: finite(record.current_price), marketCap: finite(record.market_cap), volume: finite(record.total_volume), change24h: finite(record.price_change_percentage_24h), change7d: record.price_change_percentage_7d_in_currency ?? null, sparkline: (record.sparkline_in_7d?.price ?? []).filter((price) => Number.isFinite(price)), lastUpdated: record.last_updated ?? null })); }
export function selectMovers(coins: MarketCoin[], direction: "gainers" | "decliners", limit = 20) { return coins.filter((coin) => { const isLiquid = coin.volume > 1_000_000 && coin.marketCap > 5_000_000; return isLiquid && (direction === "gainers" ? coin.change24h > 0.001 : coin.change24h < -0.001); }).sort((left, right) => direction === "gainers" ? right.change24h - left.change24h : left.change24h - right.change24h).slice(0, limit); }
export function normalizeExchange(record: CoinGeckoExchange): ExchangeSummary { return { id: record.id, name: record.name, image: record.image, country: record.country ?? null, trustScore: record.trust_score ?? null, trustRank: record.trust_score_rank ?? null, volumeBtc: finite(record.trade_volume_24h_btc), url: record.url }; }
export function normalizeBinancePairs(records: BinanceTicker[]): BinancePair[] { return records.filter((record) => record.symbol.endsWith("USDT")).map((record) => ({ symbol: record.symbol, price: Number(record.lastPrice), change24h: Number(record.priceChangePercent), quoteVolume: Number(record.quoteVolume) })).filter((record) => Number.isFinite(record.price) && Number.isFinite(record.change24h) && Number.isFinite(record.quoteVolume)).sort((left, right) => right.quoteVolume - left.quoteVolume).slice(0, 12); }
export function normalizeCoinbasePairs(records: CoinbaseProduct[]): CoinbasePair[] { return records.filter((record) => record.product_type === "SPOT" && record.status === "online" && ["USD", "USDC"].includes(record.quote_currency_id ?? "")).map((record) => ({ symbol: record.product_id, price: Number(record.price), change24h: Number(record.price_percentage_change_24h), quoteVolume: Number(record.approximate_quote_24h_volume ?? 0) })).filter((record) => Number.isFinite(record.price) && Number.isFinite(record.change24h) && Number.isFinite(record.quoteVolume)).sort((left, right) => right.quoteVolume - left.quoteVolume).slice(0, 12); }

async function getCoinbaseProducts() { return requestJson<{ products?: CoinbaseProduct[] }>(`${COINBASE_BASE_URL}/products?limit=250`, { "cache-control": "no-cache" }); }

export async function getMarketSnapshot() { return cached("market-snapshot", MARKET_CACHE_MS, async () => { const marketUrl = new URL(`${COINGECKO_BASE_URL}/coins/markets`); marketUrl.search = new URLSearchParams({ vs_currency: "usd", order: "market_cap_desc", per_page: "250", page: "1", sparkline: "true", price_change_percentage: "24h,7d" }).toString(); const [marketResult, binanceResult, coinbaseResult] = await Promise.allSettled([requestJson<CoinGeckoMarket[]>(marketUrl.toString(), coinGeckoHeaders()), requestJson<BinanceTicker[]>(`${BINANCE_BASE_URL}/ticker/24hr`), getCoinbaseProducts()]); if (marketResult.status !== "fulfilled") throw new Error("Global market data is temporarily unavailable. Please retry shortly."); const coins = normalizeCoins(marketResult.value); const totalMarketCap = coins.reduce((sum, coin) => sum + coin.marketCap, 0); const totalVolume = coins.reduce((sum, coin) => sum + coin.volume, 0); const bitcoin = coins.find((coin) => coin.symbol === "BTC"); return { coins, gainers: selectMovers(coins, "gainers"), decliners: selectMovers(coins, "decliners"), overview: { totalMarketCap, totalVolume, bitcoinDominance: bitcoin && totalMarketCap ? (bitcoin.marketCap / totalMarketCap) * 100 : 0, updatedAt: new Date().toISOString() }, binance: binanceResult.status === "fulfilled" ? { status: "live" as const, pairs: normalizeBinancePairs(binanceResult.value) } : { status: "unavailable" as const, pairs: [] as BinancePair[] }, coinbase: coinbaseResult.status === "fulfilled" ? { status: "live" as const, pairs: normalizeCoinbasePairs(coinbaseResult.value.products ?? []) } : { status: "unavailable" as const, pairs: [] as CoinbasePair[] }, sources: { global: "CoinGecko Demo API • top 250 universe", binance: binanceResult.status === "fulfilled" ? "Binance Spot public ticker" : "Binance Spot temporarily unavailable", coinbase: coinbaseResult.status === "fulfilled" ? "Coinbase public products" : "Coinbase temporarily unavailable", refreshSeconds: 60 } }; }); }

export async function getCategories() { return cached("market-categories", MARKET_CACHE_MS, async () => { const records = await requestJson<CoinGeckoCategory[]>(`${COINGECKO_BASE_URL}/coins/categories`, coinGeckoHeaders()); return records.slice(0, 24).map((record) => { const marketCap = finite(record.market_cap); const absoluteChange = finite(record.market_cap_change_24h); const previousMarketCap = marketCap - absoluteChange; return { id: record.id, name: record.name, marketCap, change24h: previousMarketCap > 0 ? (absoluteChange / previousMarketCap) * 100 : 0, topCoins: record.top_3_coins ?? [] } satisfies MarketCategory; }); }); }

export async function getCategoryCoins(categoryId: string) { return cached(`market-category-${categoryId}`, MARKET_CACHE_MS, async () => { const categoryUrl = new URL(`${COINGECKO_BASE_URL}/coins/markets`); categoryUrl.search = new URLSearchParams({ vs_currency: "usd", category: categoryId, order: "market_cap_desc", per_page: "250", page: "1", sparkline: "true", price_change_percentage: "24h,7d" }).toString(); const records = await requestJson<CoinGeckoMarket[]>(categoryUrl.toString(), coinGeckoHeaders()); return { categoryId, coins: normalizeCoins(records), updatedAt: new Date().toISOString() }; }); }

export async function getExchanges() { return cached("market-exchanges", MARKET_CACHE_MS, async () => { const [exchangeResult, binanceResult, coinbaseResult] = await Promise.allSettled([requestJson<CoinGeckoExchange[]>(`${COINGECKO_BASE_URL}/exchanges?per_page=24&page=1`, coinGeckoHeaders()), requestJson<BinanceTicker[]>(`${BINANCE_BASE_URL}/ticker/24hr`), getCoinbaseProducts()]); if (exchangeResult.status !== "fulfilled") throw new Error("Exchange market data is temporarily unavailable. Please retry shortly."); return { exchanges: exchangeResult.value.map(normalizeExchange), binance: binanceResult.status === "fulfilled" ? { status: "live" as const, pairs: normalizeBinancePairs(binanceResult.value) } : { status: "unavailable" as const, pairs: [] as BinancePair[] }, coinbase: coinbaseResult.status === "fulfilled" ? { status: "live" as const, pairs: normalizeCoinbasePairs(coinbaseResult.value.products ?? []) } : { status: "unavailable" as const, pairs: [] as CoinbasePair[] }, updatedAt: new Date().toISOString() }; }); }
